name: Question
description: Ask a question about using Custodian
labels: [kind/question]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question!
  - type: textarea
    id: question
    attributes:
      label: Ask your question
      description: A clear and concise description of what your trying to do, as well as the underlying use case.
      placeholder: What were you expecting to happen?
      value: "I am trying to get custodian to do this ..."  
  - type: textarea
    id: policy
    attributes:
      label: Policy
      description: Please copy and paste the policy you're trying to run if applicable. Please exclude any account/sensitive information. This will be automatically formatted into code, so no need for backticks.  
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log/traceback output
      description: Please copy and paste any relevant log output. Please exclude any account/sensitive information. This will be automatically formatted into code, so no need for backticks.
      render: shell